spring:
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 395065386752-4j0n5kj7fsol7jggjje7gojk41uflqbv.apps.googleusercontent.com
            clientSecret: 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
            scope:
              - email
              - profile

